"""empty message

Revision ID: 68352e7264a5
Revises: b13ba29373ca
Create Date: 2018-10-16 19:50:51.092006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68352e7264a5'
down_revision = 'b13ba29373ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('sensor_id', sa.Integer(), nullable=True))
    op.drop_constraint('alerts_ibfk_1', 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'sensors', ['sensor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('alerts', 'data_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key('alerts_ibfk_1', 'alerts', 'datas', ['data_id'], ['id'], ondelete='CASCADE')
    op.drop_column('alerts', 'sensor_id')
    # ### end Alembic commands ###
