"""empty message

Revision ID: b13ba29373ca
Revises: 352cbd6cf7ae
Create Date: 2018-10-16 16:50:25.476327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13ba29373ca'
down_revision = '352cbd6cf7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alerts_ibfk_1', 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'datas', ['data_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('datas_ibfk_1', 'datas', type_='foreignkey')
    op.create_foreign_key(None, 'datas', 'sensors', ['sensor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('devices_ibfk_1', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('news_ibfk_1', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sensors_ibfk_1', 'sensors', type_='foreignkey')
    op.create_foreign_key(None, 'sensors', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'sensors', type_='foreignkey')
    op.create_foreign_key('sensors_ibfk_1', 'sensors', 'devices', ['device_id'], ['id'])
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_ibfk_1', 'news', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_ibfk_1', 'devices', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'datas', type_='foreignkey')
    op.create_foreign_key('datas_ibfk_1', 'datas', 'sensors', ['sensor_id'], ['id'])
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key('alerts_ibfk_1', 'alerts', 'datas', ['data_id'], ['id'])
    # ### end Alembic commands ###
